# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
JAVASCRIPT_DEFAULT_STYLE: prettier
DISABLE: SPELL
DISABLE_LINTERS: PYTHON_MYPY, PYTHON_PYRIGHT  # We don't use static typing
HTML_DJLINT_ARGUMENTS: "--profile jinja"
PYTHON_PYLINT_ARGUMENTS: "--disable import-error"
