---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint & Test Code Base

#############################
# Start the job on all pull requests #
#############################
on: push

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_HTML: false
          JAVASCRIPT_DEFAULT_STYLE: prettier
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KUBERNETES_KUBECONFORM_OPTIONS: -ignore-missing-schemas
  # test:
  #   name: Test Code Base
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set Up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'
  #     - name: Install Dependencies
  #       run: | # apt packages needed for python3-saml, which is dependent on xmlsec
  #         sudo apt-get update
  #         sudo apt-get install -y pkg-config libxml2-dev libxmlsec1-dev libxmlsec1-openssl
  #         pip install dashboard/src pytest pytest-cov pytest-mock
  #     - name: Test with pytest
  #       run: pytest . --cov
