---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint & Test Code Base

#############################
# Start the job on all pull requests #
#############################
on:
  push

jobs:
  # Python Linters
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Specify your Python version
          # cache: 'pip' # Optional: cache pip dependencies
          # cache-dependency-path: '**/requirements-lint.txt' # Or your relevant requirements file

      - name: Install ruff
        run: |
          pip install ruff
      - name: Run Flake8
        run: |
          ruff check .
          ruff format --check .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install mypy and type stubs
        run: |
          pip install mypy

      - name: Run mypy
        run: |
          mypy .

  StandardJS:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-node@v4

      - name: Install standard
        run: |
          npm install standard

      - name: Run standard
        run: |
          npx standard .

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-node@v4

      - name: Install eslint
        run: npm install eslint eslint-plugin-jsonc


      - name: Run standard
        run: npx eslint .
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install gitleaks -y
      - name: Run gitleaks
        run: gitleaks git

  test:
    name: Test Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install -r .github/workflows/requirements-pytest.txt
      - name: Test with pytest
        run: pytest . --cov
