---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint & Test Code Base

#############################
# Start the job on all pull requests #
#############################
on: push

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python Linters
        run: |
          pip install ruff djlint pylint mypy yamllint
          ruff .
          ruff format .
          djlint .
          mypy .
          yamllint .
        continue-on-error: true
      - uses: actions/setup-node@v4
      - run: |
          npm install stylelint prettier jscpd
          npx stylelint .
          npx prettier --check .
          npx jscpd .
        continue-on-error: true
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: dashboard/Dockerfile

          
    # name: Test Code Base
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v4
    #   - name: Set Up Python
    #     uses: actions/setup-python@v5
    #     with:
    #       python-version: '3.x'
    #   - name: Install Dependencies
    #     run: | # apt packages needed for python3-saml, which is dependent on xmlsec
    #       sudo apt-get update
    #       sudo apt-get install -y pkg-config libxml2-dev libxmlsec1-dev libxmlsec1-openssl
    #       pip install dashboard/src pytest pytest-cov pytest-mock
    #   - name: Test with pytest
    #     run: pytest . --cov
