---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint & Test Code Base

#############################
# Start the job on all pull requests #
#############################
on:
  push

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
          # If you have a requirements.txt for linters or project dependencies:
          # pip install -r requirements-dev.txt # or requirements.txt

      - name: Run Black Linter
        # This step will flag an error if Black finds issues, but the job will continue
        continue-on-error: true
        run: |
          echo "::group::Black Output"
          black --check .
          echo "::endgroup::"
          if [ $? -ne 0 ]; then
            echo "::error title=Black Linter Failed::Black found formatting issues. Please run 'black .' to fix them."
            # exit 1 # Optionally, you can still exit with 1 to ensure the step is marked as failed clearly
          fi

      - name: Run Flake8 Linter
        # This step will flag an error if Flake8 finds issues, but the job will continue
        continue-on-error: true
        run: |
          echo "::group::Flake8 Output"
          flake8 .
          echo "::endgroup::"
          if [ $? -ne 0 ]; then
            echo "::error title=Flake8 Linter Failed::Flake8 found style issues. Please check the output above for details."
            # exit 1 # Optionally, you can still exit with 1 to ensure the step is marked as failed clearly
          fi

  test:
    name: Test Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install -r .github/workflows/requirements-pytest.txt
      - name: Test with pytest
        run: pytest . --cov
